### PR TITLE
Added the Side navigation bar and Recycler View to the Home UI

### PR DESCRIPTION
**Pull request by mdzaidalam52**

### CODE REVIEW

**Review by krharsh17 — CHANGES_REQUESTED** [review]
This is not how you define a navigation bar, it is clearly broken. Please go through https://github.com/krharsh17/informza to look at the most common way of implementing the navbar. Also, the recycler isn't visible currently due to the navbar, so please fix it asap so that I may review other code.

**Comment by krharsh17** [comment]
Also, please put only those files in the PR which fall under the `src/` folder, please remove all files from the `.idea/` folder from the PR.

**Comment by krharsh17** [comment]
@mdzaidalam52 Is this PR still valid?

**Comment by mdzaidalam52** [comment]
> 
> 
> @mdzaidalam52 Is this PR still valid?

yes

**Pull request closed without merging**
